export const site = {
  name: "Hobe Sound Farms",
  tagline: "126 acres of real Florida.",
  blurb:
    "A working farm destination with weekend markets, animal encounters, live music, and celebrations under the South Florida sky.",
  address: "1425 SE Bridge Road, Hobe Sound, FL 33455",
  phone: "(844) 462-3763",
  phoneHref: "tel:+18444623763",
  marketHours: "Sat & Sun 9am – 2pm",
  standHours: "Mon – Fri 9am – 4pm",
};

export const intents = [
  { label: "Visit the farmers market", href: "/#market", hint: "60+ vendors" },
  { label: "Meet the farm animals", href: "/animals", hint: "Petting zoo & more" },
  { label: "Host a private event", href: "/experiences#celebrate", hint: "Birthdays & corporate" },
  { label: "Say I do at the farm", href: "/experiences#weddings", hint: "Weddings" },
  { label: "Farm After Dark", href: "/events#after-dark", hint: "Music & dancing" },
  { label: "Plan a field trip", href: "/experiences#field-trips", hint: "Schools & groups" },
  { label: "Shop the farm stand", href: "/#market", hint: "Produce, eggs, honey, beef" },
  { label: "Become a vendor", href: "/#contact", hint: "Apply to sell" },
] as const;

export const animals = [
  {
    slug: "biscuit-gravy",
    species: "Nigerian Dwarf Goats",
    name: "Biscuit & Gravy",
    blurb:
      "These two will steal your snacks and your heart. Best friends since birth, always causing chaos together.",
    story:
      "You'll usually find them at the front of Animal Alley, negotiating for carrot bits with anyone who makes eye contact.",
    image: "/images/animal-goats.jpg",
    alt: "Friendly goats at the petting zoo",
  },
  {
    slug: "luna",
    species: "White-Tailed Deer",
    name: "Luna",
    blurb: "Rescued as a fawn, Luna now greets visitors at the fence every weekend without fail.",
    story:
      "Quiet, curious, and camera-ready — Luna is the soft heartbeat of the deer sanctuary.",
    image: "/images/animal-deer.jpg",
    alt: "A young deer at the farm sanctuary",
  },
  {
    slug: "churro-nacho",
    species: "Miniature Donkeys",
    name: "Churro & Nacho",
    blurb: "Louder than you'd expect. More loveable than you'd believe.",
    story:
      "Churro bites the carrots — not people. Usually. Nacho provides the soundtrack.",
    image: "/images/animal-donkey.jpg",
    alt: "A miniature donkey looking at the camera",
  },
  {
    slug: "the-flock",
    species: "Indio Gigante Chickens",
    name: "The Flock",
    blurb: "Standing nearly three feet tall — the most photographed residents on the farm.",
    story:
      "House of the Giants isn't a nickname. Come see why kids (and adults) stop mid-sentence.",
    image: "/images/animal-chickens.jpg",
    alt: "Tall colorful chickens on the farm",
  },
  {
    slug: "colony-7",
    species: "Honey Bees",
    name: "Colony 7",
    blurb: "Tens of thousands strong — busy makers of raw Florida wildflower honey.",
    story:
      "Their honey shows up at the farm stand and market every week. Taste the acreage.",
    image: "/images/animal-bees.jpg",
    alt: "Honeybees on honeycomb",
  },
  {
    slug: "barn-flutter",
    species: "Butterfly Garden",
    name: "The Barn Flutter",
    blurb: "Hundreds of native Florida butterflies in a walk-through habitat.",
    story:
      "Slow down here. It resets every visitor who thought they were just coming for produce.",
    image: "/images/animal-butterflies.jpg",
    alt: "Butterflies in a garden habitat",
  },
] as const;

export const events = [
  {
    id: "merica",
    title: "'Merica… Farm Yeah!",
    when: "Seasonal · Summer sendoff",
    price: "Tickets vary",
    desc: "The ultimate summer sendoff at Hobe Sound Farms — music, food, and full-farm energy.",
    image: "/images/event-festival.jpg",
    alt: "Crowd enjoying an outdoor farm festival",
    cta: "Get tickets",
    href: "/#tickets",
  },
  {
    id: "market",
    title: "Weekend Farmers Market",
    when: "Every Sat & Sun · 9am – 2pm",
    price: "Free entry",
    desc: "60+ vendors, farm activities, food trucks, live music, and animals — the weekly ritual.",
    image: "/images/event-market.jpg",
    alt: "Farmers market stalls with fresh produce",
    cta: "Plan your visit",
    href: "/#market",
  },
  {
    id: "line-dancing",
    title: "Line Dancing",
    when: "Select evenings",
    price: "See calendar",
    desc: "Good music, great company, and line dancing for all skill levels on the farm floor.",
    image: "/images/event-dancing.jpg",
    alt: "People line dancing outdoors",
    cta: "Join the night",
    href: "/#contact",
  },
  {
    id: "after-dark",
    title: "Farm After Dark",
    when: "Evening events",
    price: "From $15",
    desc: "Live music, night-market vibes, and the farm lit for after-hours fun.",
    image: "/images/event-night.jpg",
    alt: "Evening outdoor event with warm lights",
    cta: "Get tickets",
    href: "/#tickets",
  },
] as const;

export const farmZones = [
  {
    id: "animal-alley",
    label: "Animal Alley",
    desc: "Meet goats, donkeys, and friends along the main animal walk.",
    color: "#f0c95a",
    x: 120,
    y: 260,
    w: 140,
    h: 100,
    rx: 40,
  },
  {
    id: "petting-zoo",
    label: "Petting Zoo",
    desc: "Hands-on animal encounters — the kids' favorite stop.",
    color: "#e8b84a",
    x: 280,
    y: 270,
    w: 120,
    h: 90,
    rx: 20,
  },
  {
    id: "hen-house",
    label: "Hen House",
    desc: "Home base for the flock, including our giant Indio Gigantes.",
    color: "#d4a017",
    x: 120,
    y: 390,
    w: 130,
    h: 70,
    rx: 12,
  },
  {
    id: "gem-jungle",
    label: "Gem Jungle",
    desc: "Lush exploration zone packed with photo moments.",
    color: "#5a9e6a",
    x: 360,
    y: 360,
    w: 140,
    h: 110,
    rx: 14,
  },
  {
    id: "duck-pond",
    label: "Duck Pond",
    desc: "Quiet water, busy ducks, and shade on warm days.",
    color: "#6bb3c4",
    x: 530,
    y: 380,
    w: 120,
    h: 90,
    rx: 40,
  },
  {
    id: "main-stage",
    label: "Main Stage",
    desc: "Live music for market days and special events.",
    color: "#2f7a8a",
    x: 460,
    y: 120,
    w: 160,
    h: 60,
    rx: 10,
  },
  {
    id: "sunflower-barn",
    label: "Sunflower Barn",
    desc: "Gathering space for celebrations and seasonal moments.",
    color: "#c8b89a",
    x: 460,
    y: 210,
    w: 160,
    h: 90,
    rx: 10,
  },
  {
    id: "vendor-row",
    label: "Vendor Row",
    desc: "Produce, crafts, hot food, and local makers every weekend.",
    color: "#8fbc6e",
    x: 120,
    y: 140,
    w: 280,
    h: 80,
    rx: 10,
  },
  {
    id: "coconut-hut",
    label: "Coconut Hut",
    desc: "A shady hangout with island energy.",
    color: "#f0d890",
    x: 660,
    y: 280,
    w: 100,
    h: 70,
    rx: 12,
  },
  {
    id: "farm-stand",
    label: "Farm Stand",
    desc: "Weekday pickup for produce, eggs, honey, and local beef.",
    color: "#d4a017",
    x: 660,
    y: 180,
    w: 100,
    h: 70,
    rx: 10,
  },
] as const;

export const vendors = [
  {
    name: "Sun & Soil Farm",
    category: "produce",
    tag: "Produce",
    desc: "Seasonal vegetables grown right here in Martin County.",
  },
  {
    name: "Hobe Honey Co.",
    category: "produce",
    tag: "Honey",
    desc: "Raw Florida wildflower honey, comb honey, and beeswax.",
  },
  {
    name: "Cypress Bakehouse",
    category: "bakery",
    tag: "Bakery",
    desc: "Sourdough, croissants, and seasonal pastries.",
  },
  {
    name: "Marisol's Kitchen",
    category: "food",
    tag: "Hot Food",
    desc: "Cuban and Caribbean street food — tamales, empanadas, juice.",
  },
  {
    name: "Native Roots Nursery",
    category: "plants",
    tag: "Plants",
    desc: "Florida-native plants, orchids, and hand-painted pots.",
  },
  {
    name: "Indigo & Oak",
    category: "crafts",
    tag: "Crafts",
    desc: "Handmade textiles, macramé, and woven wall art.",
  },
  {
    name: "Golden Hour Wellness",
    category: "wellness",
    tag: "Wellness",
    desc: "Herbal tinctures, aromatherapy, and natural salves.",
  },
  {
    name: "The Fish Co.",
    category: "food",
    tag: "Seafood",
    desc: "Local fish, smoked fish dip, and seasonal stone crab.",
  },
  {
    name: "Lemon Tree Lemonade",
    category: "food",
    tag: "Beverages",
    desc: "Fresh lemonade in rotating flavors — a market favorite.",
  },
  {
    name: "Pottery by Paz",
    category: "crafts",
    tag: "Pottery",
    desc: "Handthrown ceramics made in Stuart, FL.",
  },
  {
    name: "Tropic Spice Co.",
    category: "produce",
    tag: "Specialty",
    desc: "Small-batch hot sauces, spice blends, and preserves.",
  },
  {
    name: "Green Body Co.",
    category: "wellness",
    tag: "Skincare",
    desc: "Aloe gels, sea salt scrubs, and mineral sunscreens.",
  },
] as const;

export const vendorFilters = [
  { id: "all", label: "All" },
  { id: "produce", label: "Produce" },
  { id: "food", label: "Hot Food" },
  { id: "bakery", label: "Bakery" },
  { id: "plants", label: "Plants" },
  { id: "crafts", label: "Crafts" },
  { id: "wellness", label: "Wellness" },
] as const;

export const experiences = [
  {
    id: "weddings",
    tag: "Weddings",
    title: "Say I do on 126 acres",
    desc: "Barn and outdoor celebrations surrounded by working farmland — intimate or full guest list.",
    image: "/images/exp-wedding.jpg",
    alt: "Outdoor wedding celebration at a farm",
    href: "/#contact",
  },
  {
    id: "field-trips",
    tag: "Education",
    title: "School field trips",
    desc: "Hands-on farm tours for classes — animals, crops, bees, and memories that stick.",
    image: "/images/exp-fieldtrip.jpg",
    alt: "Children on a farm field trip",
    href: "/#contact",
  },
  {
    id: "celebrate",
    tag: "Celebrations",
    title: "Birthdays & private events",
    desc: "Private farm parties with animal meet-and-greets, space to gather, and room to play.",
    image: "/images/exp-birthday.jpg",
    alt: "Outdoor birthday celebration",
    href: "/#contact",
  },
  {
    id: "after-dark-exp",
    tag: "Nightlife",
    title: "Farm After Dark",
    desc: "Live music, line dancing, and night-market energy when the sun drops.",
    image: "/images/exp-afterdark.jpg",
    alt: "Live music event after dark",
    href: "/events#after-dark",
  },
] as const;

export const tickets = [
  {
    name: "Farm Explorer Day",
    priceLabel: "$25",
    amountCents: 2500,
    features: ["Animal encounters", "Farm activities", "Kids adventure day", "Adults free with child"],
    featured: false,
  },
  {
    name: "Farm After Dark",
    priceLabel: "$15",
    amountCents: 1500,
    features: ["Evening admission", "Live music access", "Night-market vibes", "Demo Square checkout"],
    featured: true,
  },
] as const;
